// =============================================
//  MINI MARKET — i18n Translations
//  Languages: English (en), French (fr), Arabic (ar)
// =============================================

const TRANSLATIONS = {

  en: {
    dir: "ltr", lang: "English", flag: "🇬🇧",
    brandName: "Mini Market", brandTagline: "Curated second-hand marketplace",
    auth_welcome: "Welcome back",
    auth_chooseRole: "Choose your role to explore this demo",
    auth_email: "Email", auth_password: "Password",
    auth_signIn: "Sign In", auth_signingIn: "Signing in…",
    auth_noAccount: "No account?", auth_register: "Register here →",
    auth_thenSignIn: "then sign in",
    auth_heroStat: "12,000+ happy members · 2,400+ listings",
    role_admin: "Store Admin", role_admin_desc: "Full dashboard & management access",
    role_seller: "Seller", role_seller_desc: "Manage your listings & profile",
    role_buyer: "Buyer", role_buyer_desc: "Browse, wishlist & purchase items",
    nav_overview: "Overview", nav_manage: "Manage", nav_storefront: "Storefront",
    nav_myAccount: "My Account", nav_marketplace: "Marketplace",
    nav_store: "Store Dashboard", nav_products: "Products", nav_sellers: "Sellers",
    nav_buyers: "Buyers", nav_viewStore: "View Store", nav_myProfile: "My Profile",
    nav_myListings: "My Listings", nav_addItem: "Add New Item",
    nav_browseStore: "Browse Store", nav_myPurchases: "My Purchases",
    nav_wishlist: "Wishlist", nav_signOut: "← Sign Out",
    topbar_store: "Store Dashboard", topbar_products: "Products",
    topbar_sellers: "Sellers", topbar_buyers: "Buyers", topbar_storefront: "Storefront",
    topbar_sellerProfile: "My Profile", topbar_sellerListings: "My Listings",
    topbar_sellerAdd: "Add Item", topbar_buyerProfile: "My Profile",
    topbar_buyerPurchases: "My Purchases", topbar_buyerWishlist: "Wishlist",
    topbar_help: "Help", topbar_notifications: "Notifications",
    dash_eyebrow: "Overview", dash_exportReport: "📊 Export", dash_addListing: "+ Add Listing",
    dash_totalRevenue: "Total Revenue", dash_totalOrders: "Total Orders",
    dash_totalMembers: "Total Members", dash_avgRating: "Avg Rating",
    dash_vsLastMonth: "vs last month", dash_thisMonth: "this month",
    dash_reviewsBase: "Based on 847 reviews", dash_newMembers: "New Members",
    dash_salesByCategory: "Sales by Category", dash_items: "items",
    dash_recentActivity: "Recent Activity", dash_topSellers: "Top Sellers",
    dash_viewAll: "View all →", dash_sales: "sales", dash_revenue: "Revenue",
    prod_eyebrow: "Management", prod_title: "Products", prod_available: "available",
    prod_addProduct: "+ Add Product", prod_searchPlaceholder: "Search products…",
    prod_allCategories: "All Categories",
    prod_col_product: "Product", prod_col_category: "Category", prod_col_price: "Price",
    prod_col_seller: "Seller", prod_col_status: "Status",
    prod_col_engagement: "Engagement", prod_col_actions: "Actions",
    prod_view: "View", prod_edit: "Edit", prod_delete: "Del",
    prod_confirmDelete: "Delete this product?", prod_deleted: "Product deleted",
    prod_noResults: "No products found",
    addProd_title: "Add New Product", editProd_title: "Edit Product",
    form_title: "Title", form_title_ph: "e.g. Levi's 501 Jeans",
    form_price: "Price ($)", form_category: "Category", form_condition: "Condition",
    form_brand: "Brand", form_seller: "Seller", form_description: "Description",
    form_desc_ph: "Describe the item…", form_emojiIcon: "Emoji Icon",
    form_size: "Size", form_size_ph: "S / M / 42 / —", form_status: "Status",
    form_cancel: "Cancel", form_save: "Save Changes",
    form_add: "Add Product", form_listItem: "📤 List Item",
    form_required: "Please fill all required fields",
    form_nameRequired: "Name is required",
    prod_added: "added successfully!", prod_updated: "Product updated!",
    cond_likeNew: "Like New", cond_veryGood: "Very Good",
    cond_good: "Good", cond_newTags: "New with Tags",
    status_available: "Available", status_sold: "Sold", status_soldOut: "Sold Out",
    sell_eyebrow: "Management", sell_title: "Sellers",
    sell_registered: "registered sellers", sell_addSeller: "+ Add Seller",
    sell_col_seller: "Seller", sell_col_location: "Location",
    sell_col_sales: "Sales", sell_col_revenue: "Revenue",
    sell_col_rating: "Rating", sell_col_badge: "Badge", sell_col_actions: "Actions",
    sell_profile: "Profile", sell_delete: "Del",
    sell_confirmDelete: "Remove this seller?", sell_removed: "Seller removed",
    sell_joined: "Joined",
    addSell_title: "Add New Seller",
    form_fullName: "Full Name", form_fullName_ph: "e.g. Sara Johnson",
    form_location: "Location", form_location_ph: "City, Country",
    form_bio: "Bio", form_bio_ph: "Short seller bio…",
    form_avatarEmoji: "Avatar Emoji", form_badge: "Badge",
    badge_verified: "Verified", badge_topSeller: "Top Seller", badge_risingStar: "Rising Star",
    sell_addBtn: "Add Seller", sell_added: "added as seller!",
    sell_backToSellers: "← Back to Sellers",
    sell_activeListings: "Active Listings", sell_reviews: "Reviews",
    sell_noListings: "No listings yet", sell_noReviews: "No reviews yet",
    sell_editProfile: "✏️ Edit Profile", sell_editTitle: "Edit Profile",
    sell_profileUpdated: "Profile updated!",
    myList_eyebrow: "My Store", myList_title: "My Listings",
    myList_active: "active", myList_addNew: "+ Add New Item",
    myList_empty: "No listings yet", myList_emptyDesc: "Add your first item to start selling!",
    addItem_eyebrow: "Sell Something", addItem_title: "Add New Item",
    form_itemTitle: "Item Title *", form_itemTitle_ph: "e.g. Vintage Denim Jacket",
    form_priceReq: "Price ($) *", form_descReq: "Description *",
    form_descReq_ph: "Describe your item honestly — condition, history, any flaws…",
    addItem_listed: "listed successfully!",
    buy_eyebrow: "Management", buy_title: "Buyers",
    buy_registered: "registered buyers", buy_addBuyer: "+ Add Buyer",
    buy_col_buyer: "Buyer", buy_col_location: "Location",
    buy_col_orders: "Orders", buy_col_spent: "Total Spent",
    buy_col_wishlist: "Wishlist", buy_col_joined: "Joined", buy_col_actions: "Actions",
    buy_profile: "Profile", buy_delete: "Del",
    buy_confirmDelete: "Remove this buyer?", buy_removed: "Buyer removed",
    buy_addBtn: "Add Buyer", buy_added: "added!", buy_bio_ph: "Short buyer bio…",
    buy_backToBuyers: "← Back to Buyers",
    buy_purchaseHistory: "Purchase History", buy_wishlistLbl: "Wishlist",
    buy_myReviews: "My Reviews",
    buy_noPurchases: "No purchases yet", buy_noWishlist: "Wishlist is empty",
    buyPurch_eyebrow: "My Account", buyPurch_title: "My Purchases",
    buyPurch_totalSpent: "total spent",
    buyPurch_empty: "No purchases yet", buyPurch_emptyDesc: "Browse the store to find great deals!",
    buyWish_eyebrow: "My Account", buyWish_title: "My Wishlist",
    buyWish_saved: "saved items",
    buyWish_empty: "Your wishlist is empty",
    buyWish_emptyDesc: "Like items in the store to save them here.",
    sf_available: "items available today",
    sf_heroLine1: "Buy & Sell", sf_heroLine2: "Used Items", sf_heroLine3: "Easily.",
    sf_heroSub: "A curated second-hand marketplace for clothes, electronics, furniture and more.",
    sf_browseItems: "Browse Items", sf_listItem: "+ List an Item",
    sf_latestItems: "Latest Items", sf_searchPh: "Search…", sf_noItems: "No items found",
    sf_cat_all: "All", sf_cat_clothes: "Clothes", sf_cat_shoes: "Shoes",
    sf_cat_electronics: "Electronics", sf_cat_furniture: "Furniture",
    pc_view: "View", pc_buyNow: "Buy Now", pc_likes: "likes", pc_views: "views",
    pc_addedWishlist: "Added to wishlist!",
    prod_purchasedFor: "purchased for", prod_viewSeller: "View",
    cat_clothes: "Clothes", cat_shoes: "Shoes",
    cat_electronics: "Electronics", cat_furniture: "Furniture", cat_items: "items",
    notif_title: "Notifications", notif_markAll: "Mark all read",
    notif_empty: "You're all caught up!", notif_noNew: "No new notifications",
    help_title: "Help & FAQ", help_close: "Close",
    help_q1: "How do I list an item for sale?",
    help_a1: "Sign in as a Seller, go to 'Add New Item' in the sidebar, fill in the details and click 'List Item'. Your item appears in the store immediately.",
    help_q2: "How do I buy an item?",
    help_a2: "Browse the Storefront, click 'View' on any item, then click 'Buy Now'. The item is added to your purchase history.",
    help_q3: "How do I save items to my wishlist?",
    help_a3: "Click the heart (🤍) on any product card. The item saves to your Wishlist page.",
    help_q4: "What do seller badges mean?",
    help_a4: "Top Seller = most sales, Verified = identity confirmed, Rising Star = new seller with great reviews.",
    help_q5: "How do I change the language?",
    help_a5: "Use the 🌐 button in the top bar to switch between English, French, and Arabic.",
    help_q6: "Is data saved between sessions?",
    help_a6: "This is a demo — data resets on page refresh. No backend is connected.",
    tour_skip: "Skip tour", tour_next: "Next →", tour_finish: "Got it!",
    tour_s1_title: "Welcome to Mini Market!", tour_s1_body: "This is your dashboard. Let's take a quick tour to get you started.",
    tour_s2_title: "Sidebar Navigation", tour_s2_body: "Use the sidebar to switch between sections. Each role sees different options.",
    tour_s3_title: "Language & Theme", tour_s3_body: "Use 🌐 to switch language and 🌙 to toggle dark mode — both in the top bar.",
    tour_s4_title: "You're all set!", tour_s4_body: "Explore freely. Try adding a product, browsing the store, or viewing profiles.",
    theme_dark: "Dark mode", theme_light: "Light mode",
    common_signedOut: "Signed out successfully",
    common_regSoon: "Registration coming soon!", common_exportSoon: "Export coming soon!",
    common_comingSoon: "Coming Soon", common_comingSoonDesc: "This section is under construction.",
    common_memberSince: "Member since",
  },

  fr: {
    dir: "ltr", lang: "Français", flag: "🇫🇷",
    brandName: "Mini Market", brandTagline: "Marché de seconde main sélectionné",
    auth_welcome: "Bon retour",
    auth_chooseRole: "Choisissez votre rôle pour explorer",
    auth_email: "E-mail", auth_password: "Mot de passe",
    auth_signIn: "Se connecter", auth_signingIn: "Connexion…",
    auth_noAccount: "Pas de compte ?", auth_register: "S'inscrire ici →",
    auth_thenSignIn: "puis connectez-vous",
    auth_heroStat: "12 000+ membres · 2 400+ annonces",
    role_admin: "Administrateur", role_admin_desc: "Accès complet au tableau de bord",
    role_seller: "Vendeur", role_seller_desc: "Gérez vos annonces et votre profil",
    role_buyer: "Acheteur", role_buyer_desc: "Parcourir, enregistrer et acheter",
    nav_overview: "Aperçu", nav_manage: "Gérer", nav_storefront: "Vitrine",
    nav_myAccount: "Mon Compte", nav_marketplace: "Marché",
    nav_store: "Tableau de bord", nav_products: "Produits", nav_sellers: "Vendeurs",
    nav_buyers: "Acheteurs", nav_viewStore: "Voir la boutique", nav_myProfile: "Mon Profil",
    nav_myListings: "Mes Annonces", nav_addItem: "Ajouter un article",
    nav_browseStore: "Parcourir", nav_myPurchases: "Mes Achats",
    nav_wishlist: "Favoris", nav_signOut: "← Déconnexion",
    topbar_store: "Tableau de bord", topbar_products: "Produits",
    topbar_sellers: "Vendeurs", topbar_buyers: "Acheteurs", topbar_storefront: "Vitrine",
    topbar_sellerProfile: "Mon Profil", topbar_sellerListings: "Mes Annonces",
    topbar_sellerAdd: "Ajouter", topbar_buyerProfile: "Mon Profil",
    topbar_buyerPurchases: "Mes Achats", topbar_buyerWishlist: "Favoris",
    topbar_help: "Aide", topbar_notifications: "Notifications",
    dash_eyebrow: "Aperçu", dash_exportReport: "📊 Exporter", dash_addListing: "+ Ajouter",
    dash_totalRevenue: "Revenu Total", dash_totalOrders: "Commandes Totales",
    dash_totalMembers: "Membres Totaux", dash_avgRating: "Note Moyenne",
    dash_vsLastMonth: "vs mois dernier", dash_thisMonth: "ce mois",
    dash_reviewsBase: "Basé sur 847 avis", dash_newMembers: "Nouveaux Membres",
    dash_salesByCategory: "Ventes par Catégorie", dash_items: "articles",
    dash_recentActivity: "Activité Récente", dash_topSellers: "Meilleurs Vendeurs",
    dash_viewAll: "Voir tout →", dash_sales: "ventes", dash_revenue: "Revenu",
    prod_eyebrow: "Gestion", prod_title: "Produits", prod_available: "disponibles",
    prod_addProduct: "+ Ajouter", prod_searchPlaceholder: "Rechercher…",
    prod_allCategories: "Toutes les catégories",
    prod_col_product: "Produit", prod_col_category: "Catégorie", prod_col_price: "Prix",
    prod_col_seller: "Vendeur", prod_col_status: "Statut",
    prod_col_engagement: "Engagement", prod_col_actions: "Actions",
    prod_view: "Voir", prod_edit: "Modifier", prod_delete: "Sup",
    prod_confirmDelete: "Supprimer ce produit ?", prod_deleted: "Produit supprimé",
    prod_noResults: "Aucun produit trouvé",
    addProd_title: "Ajouter un produit", editProd_title: "Modifier le produit",
    form_title: "Titre", form_title_ph: "ex. Jean Levi's 501",
    form_price: "Prix (€)", form_category: "Catégorie", form_condition: "État",
    form_brand: "Marque", form_seller: "Vendeur", form_description: "Description",
    form_desc_ph: "Décrivez l'article…", form_emojiIcon: "Icône Emoji",
    form_size: "Taille", form_size_ph: "S / M / 42 / —", form_status: "Statut",
    form_cancel: "Annuler", form_save: "Enregistrer",
    form_add: "Ajouter le produit", form_listItem: "📤 Mettre en vente",
    form_required: "Remplissez tous les champs obligatoires",
    form_nameRequired: "Le nom est obligatoire",
    prod_added: "ajouté avec succès !", prod_updated: "Produit mis à jour !",
    cond_likeNew: "Comme neuf", cond_veryGood: "Très bon état",
    cond_good: "Bon état", cond_newTags: "Neuf avec étiquettes",
    status_available: "Disponible", status_sold: "Vendu", status_soldOut: "Épuisé",
    sell_eyebrow: "Gestion", sell_title: "Vendeurs",
    sell_registered: "vendeurs inscrits", sell_addSeller: "+ Ajouter un vendeur",
    sell_col_seller: "Vendeur", sell_col_location: "Lieu",
    sell_col_sales: "Ventes", sell_col_revenue: "Revenu",
    sell_col_rating: "Note", sell_col_badge: "Badge", sell_col_actions: "Actions",
    sell_profile: "Profil", sell_delete: "Sup",
    sell_confirmDelete: "Supprimer ce vendeur ?", sell_removed: "Vendeur supprimé",
    sell_joined: "Inscrit",
    addSell_title: "Ajouter un vendeur",
    form_fullName: "Nom complet", form_fullName_ph: "ex. Sara Johnson",
    form_location: "Lieu", form_location_ph: "Ville, Pays",
    form_bio: "Bio", form_bio_ph: "Courte biographie…",
    form_avatarEmoji: "Emoji avatar", form_badge: "Badge",
    badge_verified: "Vérifié", badge_topSeller: "Meilleur Vendeur", badge_risingStar: "Étoile Montante",
    sell_addBtn: "Ajouter le vendeur", sell_added: "ajouté comme vendeur !",
    sell_backToSellers: "← Retour aux vendeurs",
    sell_activeListings: "Annonces Actives", sell_reviews: "Avis",
    sell_noListings: "Aucune annonce", sell_noReviews: "Aucun avis",
    sell_editProfile: "✏️ Modifier", sell_editTitle: "Modifier le profil",
    sell_profileUpdated: "Profil mis à jour !",
    myList_eyebrow: "Ma Boutique", myList_title: "Mes Annonces",
    myList_active: "actives", myList_addNew: "+ Nouvel article",
    myList_empty: "Aucune annonce", myList_emptyDesc: "Ajoutez votre premier article !",
    addItem_eyebrow: "Vendre quelque chose", addItem_title: "Ajouter un article",
    form_itemTitle: "Titre *", form_itemTitle_ph: "ex. Veste en jean vintage",
    form_priceReq: "Prix (€) *", form_descReq: "Description *",
    form_descReq_ph: "Décrivez honnêtement votre article…",
    addItem_listed: "mis en vente avec succès !",
    buy_eyebrow: "Gestion", buy_title: "Acheteurs",
    buy_registered: "acheteurs inscrits", buy_addBuyer: "+ Ajouter un acheteur",
    buy_col_buyer: "Acheteur", buy_col_location: "Lieu",
    buy_col_orders: "Commandes", buy_col_spent: "Total dépensé",
    buy_col_wishlist: "Favoris", buy_col_joined: "Inscrit", buy_col_actions: "Actions",
    buy_profile: "Profil", buy_delete: "Sup",
    buy_confirmDelete: "Supprimer cet acheteur ?", buy_removed: "Acheteur supprimé",
    buy_addBtn: "Ajouter", buy_added: "ajouté !", buy_bio_ph: "Courte biographie…",
    buy_backToBuyers: "← Retour aux acheteurs",
    buy_purchaseHistory: "Historique d'achats", buy_wishlistLbl: "Favoris",
    buy_myReviews: "Mes Avis",
    buy_noPurchases: "Aucun achat", buy_noWishlist: "Favoris vides",
    buyPurch_eyebrow: "Mon Compte", buyPurch_title: "Mes Achats",
    buyPurch_totalSpent: "dépensé",
    buyPurch_empty: "Aucun achat", buyPurch_emptyDesc: "Parcourez la boutique !",
    buyWish_eyebrow: "Mon Compte", buyWish_title: "Favoris",
    buyWish_saved: "articles sauvegardés",
    buyWish_empty: "Aucun favori", buyWish_emptyDesc: "Likez des articles pour les sauvegarder.",
    sf_available: "articles disponibles aujourd'hui",
    sf_heroLine1: "Achetez & Vendez", sf_heroLine2: "Facilement",
    sf_heroLine3: "des articles d'occasion.",
    sf_heroSub: "Marché de seconde main : vêtements, électronique, meubles et plus.",
    sf_browseItems: "Parcourir", sf_listItem: "+ Mettre en vente",
    sf_latestItems: "Derniers articles", sf_searchPh: "Rechercher…", sf_noItems: "Aucun résultat",
    sf_cat_all: "Tout", sf_cat_clothes: "Vêtements", sf_cat_shoes: "Chaussures",
    sf_cat_electronics: "Électronique", sf_cat_furniture: "Meubles",
    pc_view: "Voir", pc_buyNow: "Acheter", pc_likes: "j'aime", pc_views: "vues",
    pc_addedWishlist: "Ajouté aux favoris !",
    prod_purchasedFor: "acheté pour", prod_viewSeller: "Voir",
    cat_clothes: "Vêtements", cat_shoes: "Chaussures",
    cat_electronics: "Électronique", cat_furniture: "Meubles", cat_items: "articles",
    notif_title: "Notifications", notif_markAll: "Tout marquer comme lu",
    notif_empty: "Vous êtes à jour !", notif_noNew: "Aucune notification",
    help_title: "Aide & FAQ", help_close: "Fermer",
    help_q1: "Comment mettre un article en vente ?",
    help_a1: "Connectez-vous en Vendeur, allez dans 'Ajouter un article', remplissez et cliquez 'Mettre en vente'.",
    help_q2: "Comment acheter un article ?",
    help_a2: "Parcourez la vitrine, cliquez 'Voir', puis 'Acheter'. L'article s'ajoute à vos achats.",
    help_q3: "Comment sauvegarder des articles ?",
    help_a3: "Cliquez le cœur 🤍 sur une fiche. L'article se sauvegarde dans vos favoris.",
    help_q4: "Que signifient les badges ?",
    help_a4: "Meilleur Vendeur = plus de ventes, Vérifié = identité confirmée, Étoile Montante = nouveau avec bons avis.",
    help_q5: "Comment changer la langue ?",
    help_a5: "Utilisez 🌐 dans la barre du haut pour choisir Anglais, Français ou Arabe.",
    help_q6: "Les données sont-elles sauvegardées ?",
    help_a6: "C'est une démo — les données se réinitialisent au rechargement.",
    tour_skip: "Passer", tour_next: "Suivant →", tour_finish: "Compris !",
    tour_s1_title: "Bienvenue sur Mini Market !", tour_s1_body: "Voici votre tableau de bord. Faisons une visite rapide.",
    tour_s2_title: "Navigation latérale", tour_s2_body: "Utilisez la barre latérale pour naviguer entre les sections.",
    tour_s3_title: "Langue et thème", tour_s3_body: "Utilisez 🌐 pour la langue et 🌙 pour le mode sombre.",
    tour_s4_title: "Vous êtes prêt !", tour_s4_body: "Explorez la plateforme librement.",
    theme_dark: "Mode sombre", theme_light: "Mode clair",
    common_signedOut: "Déconnecté avec succès",
    common_regSoon: "Inscription bientôt disponible !",
    common_exportSoon: "Export bientôt disponible !",
    common_comingSoon: "Bientôt disponible",
    common_comingSoonDesc: "Cette section est en construction.",
    common_memberSince: "Membre depuis",
  },

  ar: {
    dir: "rtl", lang: "العربية", flag: "🇩🇿",
    brandName: "ميني ماركت", brandTagline: "سوق مختار للمستعملات",
    auth_welcome: "مرحباً بعودتك",
    auth_chooseRole: "اختر دورك لاستكشاف هذه التجربة",
    auth_email: "البريد الإلكتروني", auth_password: "كلمة المرور",
    auth_signIn: "تسجيل الدخول", auth_signingIn: "جارٍ الدخول…",
    auth_noAccount: "ليس لديك حساب؟", auth_register: "سجّل هنا ←",
    auth_thenSignIn: "ثم سجّل الدخول",
    auth_heroStat: "+١٢٬٠٠٠ عضو · +٢٬٤٠٠ إعلان",
    role_admin: "مدير المتجر", role_admin_desc: "وصول كامل للوحة التحكم",
    role_seller: "بائع", role_seller_desc: "إدارة إعلاناتك وملفك الشخصي",
    role_buyer: "مشترٍ", role_buyer_desc: "تصفح وحفظ وشراء المنتجات",
    nav_overview: "نظرة عامة", nav_manage: "الإدارة", nav_storefront: "الواجهة",
    nav_myAccount: "حسابي", nav_marketplace: "السوق",
    nav_store: "لوحة التحكم", nav_products: "المنتجات", nav_sellers: "البائعون",
    nav_buyers: "المشترون", nav_viewStore: "عرض المتجر", nav_myProfile: "ملفي الشخصي",
    nav_myListings: "إعلاناتي", nav_addItem: "إضافة منتج",
    nav_browseStore: "تصفح المتجر", nav_myPurchases: "مشترياتي",
    nav_wishlist: "قائمة الأمنيات", nav_signOut: "تسجيل الخروج →",
    topbar_store: "لوحة التحكم", topbar_products: "المنتجات",
    topbar_sellers: "البائعون", topbar_buyers: "المشترون", topbar_storefront: "الواجهة",
    topbar_sellerProfile: "ملفي الشخصي", topbar_sellerListings: "إعلاناتي",
    topbar_sellerAdd: "إضافة", topbar_buyerProfile: "ملفي الشخصي",
    topbar_buyerPurchases: "مشترياتي", topbar_buyerWishlist: "الأمنيات",
    topbar_help: "المساعدة", topbar_notifications: "الإشعارات",
    dash_eyebrow: "نظرة عامة", dash_exportReport: "📊 تصدير", dash_addListing: "+ إضافة",
    dash_totalRevenue: "إجمالي الإيرادات", dash_totalOrders: "إجمالي الطلبات",
    dash_totalMembers: "إجمالي الأعضاء", dash_avgRating: "متوسط التقييم",
    dash_vsLastMonth: "مقارنة بالشهر الماضي", dash_thisMonth: "هذا الشهر",
    dash_reviewsBase: "بناءً على ٨٤٧ تقييم", dash_newMembers: "أعضاء جدد",
    dash_salesByCategory: "المبيعات حسب الفئة", dash_items: "منتج",
    dash_recentActivity: "النشاط الأخير", dash_topSellers: "أفضل البائعين",
    dash_viewAll: "← عرض الكل", dash_sales: "مبيعات", dash_revenue: "الإيرادات",
    prod_eyebrow: "الإدارة", prod_title: "المنتجات", prod_available: "متاح",
    prod_addProduct: "+ إضافة منتج", prod_searchPlaceholder: "البحث عن منتجات…",
    prod_allCategories: "جميع الفئات",
    prod_col_product: "المنتج", prod_col_category: "الفئة", prod_col_price: "السعر",
    prod_col_seller: "البائع", prod_col_status: "الحالة",
    prod_col_engagement: "التفاعل", prod_col_actions: "الإجراءات",
    prod_view: "عرض", prod_edit: "تعديل", prod_delete: "حذف",
    prod_confirmDelete: "حذف هذا المنتج؟", prod_deleted: "تم حذف المنتج",
    prod_noResults: "لا توجد منتجات",
    addProd_title: "إضافة منتج جديد", editProd_title: "تعديل المنتج",
    form_title: "العنوان", form_title_ph: "مثال: جينز ليفايز ٥٠١",
    form_price: "السعر ($)", form_category: "الفئة", form_condition: "الحالة",
    form_brand: "العلامة التجارية", form_seller: "البائع", form_description: "الوصف",
    form_desc_ph: "صف المنتج…", form_emojiIcon: "رمز تعبيري",
    form_size: "المقاس", form_size_ph: "S / M / 42 / —", form_status: "الحالة",
    form_cancel: "إلغاء", form_save: "حفظ التغييرات",
    form_add: "إضافة المنتج", form_listItem: "📤 نشر الإعلان",
    form_required: "يرجى ملء جميع الحقول المطلوبة",
    form_nameRequired: "الاسم مطلوب",
    prod_added: "أُضيف بنجاح!", prod_updated: "تم تحديث المنتج!",
    cond_likeNew: "كالجديد", cond_veryGood: "جيد جداً",
    cond_good: "جيد", cond_newTags: "جديد بالبطاقات",
    status_available: "متاح", status_sold: "مباع", status_soldOut: "نفد المخزون",
    sell_eyebrow: "الإدارة", sell_title: "البائعون",
    sell_registered: "بائع مسجّل", sell_addSeller: "+ إضافة بائع",
    sell_col_seller: "البائع", sell_col_location: "الموقع",
    sell_col_sales: "المبيعات", sell_col_revenue: "الإيرادات",
    sell_col_rating: "التقييم", sell_col_badge: "الشارة", sell_col_actions: "الإجراءات",
    sell_profile: "الملف", sell_delete: "حذف",
    sell_confirmDelete: "إزالة هذا البائع؟", sell_removed: "تمت إزالة البائع",
    sell_joined: "انضم في",
    addSell_title: "إضافة بائع جديد",
    form_fullName: "الاسم الكامل", form_fullName_ph: "مثال: سارة جونسون",
    form_location: "الموقع", form_location_ph: "المدينة، الدولة",
    form_bio: "نبذة", form_bio_ph: "نبذة قصيرة عن البائع…",
    form_avatarEmoji: "رمز الصورة", form_badge: "الشارة",
    badge_verified: "موثّق", badge_topSeller: "أفضل بائع", badge_risingStar: "نجم صاعد",
    sell_addBtn: "إضافة البائع", sell_added: "أُضيف كبائع!",
    sell_backToSellers: "← العودة للبائعين",
    sell_activeListings: "الإعلانات النشطة", sell_reviews: "التقييمات",
    sell_noListings: "لا توجد إعلانات", sell_noReviews: "لا توجد تقييمات",
    sell_editProfile: "✏️ تعديل الملف", sell_editTitle: "تعديل الملف الشخصي",
    sell_profileUpdated: "تم تحديث الملف!",
    myList_eyebrow: "متجري", myList_title: "إعلاناتي",
    myList_active: "نشط", myList_addNew: "+ إعلان جديد",
    myList_empty: "لا توجد إعلانات", myList_emptyDesc: "أضف أول منتج لك وابدأ البيع!",
    addItem_eyebrow: "بيع شيء ما", addItem_title: "إضافة منتج جديد",
    form_itemTitle: "عنوان المنتج *", form_itemTitle_ph: "مثال: جاكيت جينز قديم",
    form_priceReq: "السعر ($) *", form_descReq: "الوصف *",
    form_descReq_ph: "صف منتجك بصدق — الحالة، التاريخ، أي عيوب…",
    addItem_listed: "نُشر الإعلان بنجاح!",
    buy_eyebrow: "الإدارة", buy_title: "المشترون",
    buy_registered: "مشترٍ مسجّل", buy_addBuyer: "+ إضافة مشترٍ",
    buy_col_buyer: "المشتري", buy_col_location: "الموقع",
    buy_col_orders: "الطلبات", buy_col_spent: "المبلغ المنفق",
    buy_col_wishlist: "الأمنيات", buy_col_joined: "تاريخ التسجيل", buy_col_actions: "الإجراءات",
    buy_profile: "الملف", buy_delete: "حذف",
    buy_confirmDelete: "إزالة هذا المشتري؟", buy_removed: "تمت إزالة المشتري",
    buy_addBtn: "إضافة المشتري", buy_added: "أُضيف!", buy_bio_ph: "نبذة قصيرة…",
    buy_backToBuyers: "← العودة للمشترين",
    buy_purchaseHistory: "سجل المشتريات", buy_wishlistLbl: "قائمة الأمنيات",
    buy_myReviews: "تقييماتي",
    buy_noPurchases: "لا توجد مشتريات", buy_noWishlist: "قائمة الأمنيات فارغة",
    buyPurch_eyebrow: "حسابي", buyPurch_title: "مشترياتي",
    buyPurch_totalSpent: "إجمالي الإنفاق",
    buyPurch_empty: "لا توجد مشتريات", buyPurch_emptyDesc: "تصفح المتجر للعثور على صفقات رائعة!",
    buyWish_eyebrow: "حسابي", buyWish_title: "قائمة الأمنيات",
    buyWish_saved: "منتجات محفوظة",
    buyWish_empty: "قائمة الأمنيات فارغة", buyWish_emptyDesc: "اضغط على القلب 🤍 لحفظ المنتجات.",
    sf_available: "منتج متاح اليوم",
    sf_heroLine1: "اشترِ وبع", sf_heroLine2: "المستعملات", sf_heroLine3: "بكل سهولة.",
    sf_heroSub: "سوق مختار للملابس والإلكترونيات والأثاث والمزيد.",
    sf_browseItems: "تصفح المنتجات", sf_listItem: "+ أضف إعلاناً",
    sf_latestItems: "أحدث المنتجات", sf_searchPh: "بحث…", sf_noItems: "لا توجد نتائج",
    sf_cat_all: "الكل", sf_cat_clothes: "ملابس", sf_cat_shoes: "أحذية",
    sf_cat_electronics: "إلكترونيات", sf_cat_furniture: "أثاث",
    pc_view: "عرض", pc_buyNow: "اشترِ الآن", pc_likes: "إعجابات", pc_views: "مشاهدات",
    pc_addedWishlist: "أُضيف إلى الأمنيات!",
    prod_purchasedFor: "اشتريت بـ", prod_viewSeller: "عرض",
    cat_clothes: "ملابس", cat_shoes: "أحذية",
    cat_electronics: "إلكترونيات", cat_furniture: "أثاث", cat_items: "منتج",
    notif_title: "الإشعارات", notif_markAll: "تحديد الكل كمقروء",
    notif_empty: "لا توجد إشعارات جديدة!", notif_noNew: "لا توجد إشعارات",
    help_title: "المساعدة والأسئلة الشائعة", help_close: "إغلاق",
    help_q1: "كيف أنشر إعلاناً للبيع؟",
    help_a1: "سجّل دخولك كبائع، اذهب إلى 'إضافة منتج'، أكمل التفاصيل واضغط 'نشر الإعلان'.",
    help_q2: "كيف أشتري منتجاً؟",
    help_a2: "تصفح الواجهة، اضغط 'عرض'، ثم 'اشترِ الآن'. يُضاف المنتج إلى مشترياتك.",
    help_q3: "كيف أحفظ منتجات؟",
    help_a3: "اضغط على القلب 🤍 على بطاقة أي منتج. يُحفظ في قائمة أمنياتك.",
    help_q4: "ماذا تعني الشارات؟",
    help_a4: "أفضل بائع = أكثر مبيعاً، موثّق = هوية مؤكدة، نجم صاعد = بائع جديد بتقييمات ممتازة.",
    help_q5: "كيف أغيّر اللغة؟",
    help_a5: "استخدم زر 🌐 في الشريط العلوي للتبديل بين العربية والفرنسية والإنجليزية.",
    help_q6: "هل تُحفظ البيانات؟",
    help_a6: "هذه تجربة تجريبية — تُعاد البيانات عند تحديث الصفحة.",
    tour_skip: "تخطي", tour_next: "التالي ←", tour_finish: "فهمت!",
    tour_s1_title: "مرحباً في ميني ماركت!", tour_s1_body: "هذه لوحة التحكم. دعنا نأخذ جولة سريعة.",
    tour_s2_title: "شريط التنقل", tour_s2_body: "استخدم الشريط الجانبي للتنقل. كل دور يرى خيارات مختلفة.",
    tour_s3_title: "اللغة والثيم", tour_s3_body: "استخدم 🌐 لتغيير اللغة و🌙 للوضع المظلم.",
    tour_s4_title: "أنت مستعد!", tour_s4_body: "استكشف المنصة. جرّب إضافة منتج أو تصفح المتجر.",
    theme_dark: "الوضع المظلم", theme_light: "الوضع الفاتح",
    common_signedOut: "تم تسجيل الخروج بنجاح",
    common_regSoon: "التسجيل قريباً!",
    common_exportSoon: "التصدير قريباً!",
    common_comingSoon: "قريباً",
    common_comingSoonDesc: "هذا القسم قيد الإنشاء.",
    common_memberSince: "عضو منذ",
  },
};

let currentLang = 'en';

function t(key) {
  return TRANSLATIONS[currentLang]?.[key] ?? TRANSLATIONS['en']?.[key] ?? key;
}

function setLanguage(lang) {
  if (!TRANSLATIONS[lang]) return;
  currentLang = lang;
  const dir = TRANSLATIONS[lang].dir;
  document.documentElement.setAttribute('lang', lang);
  document.documentElement.setAttribute('dir', dir);
  document.body.classList.toggle('rtl', dir === 'rtl');
}

function getLang() { return currentLang; }